"""
agents.py — LLM-powered Agent Roles for the Sandbox Backend.

CRITICAL DIFFERENCE FROM PREVIOUS VERSION:
Old version (Copilot's): Agents used template string formatting.
    Result: "По методологии X: Применяем подход к запросу." (useless)

New version: Each agent calls the LLM with a role-specific system prompt.
    Result: Real, contextual content generated by the AI itself.

This is exactly how multi-agent systems work in ChatGPT, Claude,
Kimi 2.0, etc: ONE LLM calls ITSELF in different roles:
    PlannerAgent  → LLM with planner system prompt
    ExecutorAgent → LLM with executor system prompt
    ReviewerAgent → LLM with reviewer system prompt
    CriticAgent   → LLM with critic system prompt

The chain is:
    User Query → PlannerAgent → ExecutorAgent → ReviewerAgent → CriticAgent
                                                                   │
                                          ┌────────────────────────┘
                                          ▼
                                   Accept (return result)
                                   Reject (iterate from Planner)
                                   Revise (iterate from Executor)
"""
from __future__ import annotations

import enum
import json
import time
import uuid
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

from llm_provider import LLMProvider


# ─── Agent Role Enum ────────────────────────────────────────────────────

class AgentRole(enum.Enum):
    PLANNER = "planner"
    EXECUTOR = "executor"
    REVIEWER = "reviewer"
    CRITIC = "critic"


# ─── Agent Message ──────────────────────────────────────────────────────

@dataclass
class AgentMessage:
    """Structured message passed between agents."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    role: str = ""                    # sender role
    action: str = ""                  # what action was taken
    payload: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return asdict(self)


# ─── Role-specific System Prompts ───────────────────────────────────────
# Each agent gets a DIFFERENT system prompt that shapes its behavior.
# This is the same pattern as: ChatGPT Code Interpreter vs Browsing,
# Claude's Artifacts vs Analysis, etc.

PLANNER_SYSTEM_PROMPT = """You are a PLANNER agent. Your job is to decompose a user request into a structured execution plan.

RULES:
1. Analyze the user's request carefully
2. Break it into 2-5 concrete, sequential subtasks
3. Each subtask must have: step number, type, description, expected output
4. Consider the skill methodology provided in the context
5. Identify the output format the user expects

OUTPUT FORMAT — respond with valid JSON only:
{
    "subtasks": [
        {"step": 1, "type": "understand", "description": "...", "output": "..."},
        {"step": 2, "type": "generate", "description": "...", "output": "..."}
    ],
    "methodology_hints": ["hint1", "hint2"],
    "output_format": "document|analysis|visual|research|text",
    "estimated_steps": 3
}

Be specific and actionable. Do NOT be vague."""

EXECUTOR_SYSTEM_PROMPT = """You are an EXECUTOR agent. Your job is to generate actual content based on a plan.

RULES:
1. You receive a plan with subtasks from the planner
2. For EACH subtask, produce real, substantive content
3. Follow the skill methodology strictly
4. Write in the user's language (Russian if they wrote in Russian, etc.)
5. Be specific, detailed, and actionable — NOT generic
6. Each section should be at least 3-5 sentences of real content
7. Do NOT write meta-descriptions like "here is a section about X" — WRITE the actual content
8. Do NOT use placeholder text or template phrases

OUTPUT: Write the actual deliverable content directly. No JSON wrapping needed.
Separate sections with blank lines. Use markdown headers (##) for structure."""

REVIEWER_SYSTEM_PROMPT = """You are a REVIEWER agent. Your job is to evaluate generated content against the original request.

EVALUATE:
1. Relevance: Does the content address the user's actual request?
2. Completeness: Are all aspects of the request covered?
3. Quality: Is the content specific, detailed, and actionable?
4. Structure: Is the content well-organized?
5. Substance: Is there real content, not just meta-descriptions or placeholders?

OUTPUT FORMAT — respond with valid JSON only:
{
    "verdict": "pass" or "needs_improvement",
    "scores": {
        "relevance": 0.0-1.0,
        "completeness": 0.0-1.0,
        "quality": 0.0-1.0,
        "structure": 0.0-1.0,
        "substance": 0.0-1.0
    },
    "average_score": 0.0-1.0,
    "issues": ["specific issue 1", "specific issue 2"],
    "suggestions": ["specific suggestion 1", "specific suggestion 2"]
}

Be strict. Score below 0.6 if content is generic or contains meta-descriptions instead of real content."""

CRITIC_SYSTEM_PROMPT = """You are a CRITIC agent. Your job is to make the final decision: accept, reject, or iterate.

Based on the reviewer's evaluation, decide:
- "accept": Content is good enough to return to the user (score >= 0.7)
- "reject": Content is too poor, need to restart from planning (score < 0.3)
- "iterate": Content has potential but needs revision (0.3 <= score < 0.7)

OUTPUT FORMAT — respond with valid JSON only:
{
    "decision": "accept" or "reject" or "iterate",
    "reason": "specific explanation",
    "next_agent": "planner" or "executor" or null,
    "quality_score": 0.0-1.0,
    "focus_areas": ["what to focus on in next iteration"]
}

Be decisive. If score >= 0.7, accept. If the content is fundamentally wrong, reject."""


# ─── Base Agent ─────────────────────────────────────────────────────────

class Agent:
    """Base class for all agent roles.

    Each agent receives an LLMProvider and uses it to call the LLM
    with its role-specific system prompt. This is the core mechanism:
    the SAME LLM is called with DIFFERENT role prompts, exactly like
    how multi-agent AI systems work.
    """

    role: AgentRole = AgentRole.PLANNER  # override in subclass
    system_prompt: str = PLANNER_SYSTEM_PROMPT  # override in subclass

    def __init__(self, llm: LLMProvider,
                 skill_context: Optional[Dict] = None):
        self.llm = llm
        self.skill_context = skill_context or {}
        self.history: List[AgentMessage] = []

    def process(self, message: AgentMessage) -> AgentMessage:
        """Process an incoming message and return a response."""
        self.history.append(message)
        result = self._reason(message)
        self.history.append(result)
        return result

    def _reason(self, message: AgentMessage) -> AgentMessage:
        """Override in subclass. Core reasoning via LLM call."""
        raise NotImplementedError

    def _call_llm(self, user_prompt: str) -> Optional[str]:
        """Call the LLM with this agent's role-specific system prompt."""
        return self.llm.chat(
            system_prompt=self.system_prompt,
            user_prompt=user_prompt,
        )

    def _msg(self, action: str, payload: Dict, confidence: float) -> AgentMessage:
        return AgentMessage(
            role=self.role.value,
            action=action,
            payload=payload,
            confidence=confidence,
        )


# ─── Planner Agent ──────────────────────────────────────────────────────

class PlannerAgent(Agent):
    """Decomposes a user query into structured subtasks via LLM.

    The planner calls the LLM with a planner-specific system prompt
    that instructs it to break down the request into actionable steps.
    This produces REAL plans, not template-based decompositions.
    """

    role = AgentRole.PLANNER
    system_prompt = PLANNER_SYSTEM_PROMPT

    def _reason(self, message: AgentMessage) -> AgentMessage:
        query = message.payload.get("query", "")
        skill_name = self.skill_context.get("skill_name", "unknown")
        skill_md = self.skill_context.get("skill_md", "")

        # Build the prompt for the LLM
        user_prompt = self._build_planner_prompt(query, skill_name, skill_md)

        # Call the LLM with planner system prompt
        llm_response = self._call_llm(user_prompt)

        if not llm_response:
            return self._msg(
                action="plan_created",
                payload=self._fallback_plan(query, skill_name),
                confidence=0.3,
            )

        # Parse the LLM's plan
        plan = self._parse_plan(llm_response, query, skill_name)

        return self._msg(
            action="plan_created",
            payload=plan,
            confidence=0.8 if plan.get("subtasks") else 0.4,
        )

    def _build_planner_prompt(self, query: str, skill_name: str,
                               skill_md: str) -> str:
        """Build the user prompt for the planner LLM call."""
        parts = [
            f"SKILL: {skill_name}",
            f"USER REQUEST: {query}",
        ]
        if skill_md:
            # Include skill methodology as context (truncated if too long)
            md_context = skill_md[:3000] if len(skill_md) > 3000 else skill_md
            parts.append(f"SKILL METHODOLOGY:\n{md_context}")
        parts.append("Create an execution plan for this request.")
        return "\n\n".join(parts)

    def _parse_plan(self, response: str, query: str,
                    skill_name: str) -> Dict:
        """Parse LLM response into a structured plan."""
        # Try to extract JSON from the response
        try:
            # Find JSON in the response
            json_start = response.find("{")
            json_end = response.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                plan = json.loads(response[json_start:json_end])
                # Ensure required fields
                plan.setdefault("query", query)
                plan.setdefault("skill_name", skill_name)
                plan.setdefault("subtasks", [])
                plan.setdefault("methodology_hints", [])
                plan.setdefault("output_format", "text")
                return plan
        except (json.JSONDecodeError, ValueError):
            pass

        # Fallback: treat the entire response as a single plan step
        return {
            "query": query,
            "skill_name": skill_name,
            "subtasks": [
                {"step": 1, "type": "generate",
                 "description": response[:500],
                 "output": "content"},
            ],
            "methodology_hints": [],
            "output_format": "text",
        }

    def _fallback_plan(self, query: str, skill_name: str) -> Dict:
        """Minimal plan when LLM call fails."""
        return {
            "query": query,
            "skill_name": skill_name,
            "subtasks": [
                {"step": 1, "type": "generate",
                 "description": f"Generate content for: {query[:200]}",
                 "output": "content"},
            ],
            "methodology_hints": [],
            "output_format": "text",
        }


# ─── Executor Agent ─────────────────────────────────────────────────────

class ExecutorAgent(Agent):
    """Generates real content via LLM for each subtask in the plan.

    The executor calls the LLM with an executor-specific system prompt
    that instructs it to produce actual, substantive content — not
    meta-descriptions or templates. This is where the REAL work happens.
    """

    role = AgentRole.EXECUTOR
    system_prompt = EXECUTOR_SYSTEM_PROMPT

    def _reason(self, message: AgentMessage) -> AgentMessage:
        plan = message.payload
        subtasks = plan.get("subtasks", [])
        query = plan.get("query", "")
        skill_name = plan.get("skill_name", "unknown")
        methodology_hints = plan.get("methodology_hints", [])
        output_format = plan.get("output_format", "text")

        # Build the executor prompt with full context
        user_prompt = self._build_executor_prompt(
            query, skill_name, subtasks, methodology_hints, output_format
        )

        # Call the LLM with executor system prompt
        llm_response = self._call_llm(user_prompt)

        if not llm_response:
            return self._msg(
                action="content_generated",
                payload={
                    "query": query,
                    "skill_name": skill_name,
                    "final_content": "",
                    "output_format": output_format,
                },
                confidence=0.1,
            )

        # The LLM response IS the content
        final_content = llm_response

        return self._msg(
            action="content_generated",
            payload={
                "query": query,
                "skill_name": skill_name,
                "subtask_results": [{"step": 1, "type": "generate",
                                     "content": final_content}],
                "final_content": final_content,
                "output_format": output_format,
                "sections_count": 1,
            },
            confidence=0.7,
        )

    def _build_executor_prompt(self, query: str, skill_name: str,
                                subtasks: List[Dict],
                                methodology_hints: List[str],
                                output_format: str) -> str:
        """Build the user prompt for the executor LLM call."""
        parts = [
            f"SKILL: {skill_name}",
            f"USER REQUEST: {query}",
            f"OUTPUT FORMAT: {output_format}",
        ]

        if subtasks:
            subtask_desc = "\n".join(
                f"  Step {s.get('step', i+1)}: [{s.get('type', 'generate')}] "
                f"{s.get('description', '')}"
                for i, s in enumerate(subtasks)
            )
            parts.append(f"EXECUTION PLAN:\n{subtask_desc}")

        if methodology_hints:
            parts.append(f"METHODOLOGY HINTS: {'; '.join(methodology_hints[:5])}")

        # Include skill MD context if available
        skill_md = self.skill_context.get("skill_md", "")
        if skill_md:
            md_context = skill_md[:3000] if len(skill_md) > 3000 else skill_md
            parts.append(f"SKILL METHODOLOGY:\n{md_context}")

        parts.append(
            "Now execute this plan. Write the actual content directly. "
            "Do NOT write meta-descriptions. Do NOT use placeholders. "
            "Write substantive, detailed content that addresses the user's request."
        )

        return "\n\n".join(parts)


# ─── Reviewer Agent ─────────────────────────────────────────────────────

class ReviewerAgent(Agent):
    """Evaluates generated content via LLM against the original request.

    The reviewer calls the LLM with a reviewer-specific system prompt
    that instructs it to critically evaluate quality, relevance,
    completeness, and substance. This produces REAL evaluations,
    not word-count heuristics.
    """

    role = AgentRole.REVIEWER
    system_prompt = REVIEWER_SYSTEM_PROMPT

    def _reason(self, message: AgentMessage) -> AgentMessage:
        payload = message.payload
        query = payload.get("query", "")
        final_content = payload.get("final_content", "")
        skill_name = payload.get("skill_name", "unknown")

        # Build the reviewer prompt
        user_prompt = self._build_reviewer_prompt(query, final_content, skill_name)

        # Call the LLM with reviewer system prompt
        llm_response = self._call_llm(user_prompt)

        if not llm_response:
            # Fallback: simple heuristic check
            return self._fallback_review(query, final_content, skill_name)

        # Parse the review
        review = self._parse_review(llm_response, query, skill_name)

        return self._msg(
            action="review_completed",
            payload=review,
            confidence=review.get("average_score", 0.5),
        )

    def _build_reviewer_prompt(self, query: str, content: str,
                                skill_name: str) -> str:
        """Build the user prompt for the reviewer LLM call."""
        return (
            f"SKILL: {skill_name}\n"
            f"ORIGINAL REQUEST: {query}\n\n"
            f"GENERATED CONTENT:\n{content}\n\n"
            f"Evaluate this content against the original request. "
            f"Be strict about quality and substance."
        )

    def _parse_review(self, response: str, query: str,
                      skill_name: str) -> Dict:
        """Parse LLM review response."""
        try:
            json_start = response.find("{")
            json_end = response.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                review = json.loads(response[json_start:json_end])
                review.setdefault("query", query)
                review.setdefault("skill_name", skill_name)
                review.setdefault("verdict",
                    "pass" if review.get("average_score", 0) >= 0.6
                    else "needs_improvement")
                return review
        except (json.JSONDecodeError, ValueError):
            pass

        # Fallback: treat as pass with moderate score
        return {
            "query": query,
            "skill_name": skill_name,
            "verdict": "pass",
            "scores": {"relevance": 0.7, "completeness": 0.7,
                       "quality": 0.7, "structure": 0.7, "substance": 0.7},
            "average_score": 0.7,
            "issues": [],
            "suggestions": [],
        }

    def _fallback_review(self, query: str, content: str,
                         skill_name: str) -> AgentMessage:
        """Simple heuristic review when LLM is unavailable."""
        has_content = bool(content and len(content.strip()) > 50)
        score = 0.6 if has_content else 0.2
        verdict = "pass" if has_content else "needs_improvement"

        return self._msg(
            action="review_completed",
            payload={
                "query": query,
                "skill_name": skill_name,
                "verdict": verdict,
                "scores": {"overall": score},
                "average_score": score,
                "issues": [] if has_content else ["Content is empty or too short"],
                "suggestions": [] if has_content else ["Generate substantive content"],
            },
            confidence=score,
        )


# ─── Critic Agent ───────────────────────────────────────────────────────

class CriticAgent(Agent):
    """Final decision maker via LLM: accept, reject, or iterate.

    The critic calls the LLM with a critic-specific system prompt
    that instructs it to make a strategic decision about the content's
    readiness. It also determines which agent should handle iteration.
    """

    role = AgentRole.CRITIC
    system_prompt = CRITIC_SYSTEM_PROMPT

    MAX_ITERATIONS = 3

    def __init__(self, llm: LLMProvider,
                 skill_context: Optional[Dict] = None):
        super().__init__(llm, skill_context)
        self.iteration = 0

    def _reason(self, message: AgentMessage) -> AgentMessage:
        review = message.payload
        verdict = review.get("verdict", "needs_improvement")
        avg_score = review.get("average_score", 0.0)
        issues = review.get("issues", [])
        suggestions = review.get("suggestions", [])
        query = review.get("query", "")

        self.iteration += 1

        # If max iterations reached, force accept
        if self.iteration >= self.MAX_ITERATIONS:
            return self._msg(
                action="critic_verdict",
                payload={
                    "decision": "accept",
                    "reason": f"Max iterations ({self.MAX_ITERATIONS}) reached",
                    "next_agent": None,
                    "iteration": self.iteration,
                    "quality_score": avg_score,
                    "issues_count": len(issues),
                    "suggestions": suggestions,
                    "query": query,
                },
                confidence=avg_score,
            )

        # Build the critic prompt
        user_prompt = self._build_critic_prompt(
            query, verdict, avg_score, issues, suggestions
        )

        # Call the LLM with critic system prompt
        llm_response = self._call_llm(user_prompt)

        if not llm_response:
            # Fallback: rule-based decision
            return self._fallback_critic(query, verdict, avg_score,
                                          issues, suggestions)

        # Parse the critic's decision
        return self._parse_critique(llm_response, query, avg_score,
                                     issues, suggestions)

    def _build_critic_prompt(self, query: str, verdict: str,
                              avg_score: float, issues: List[str],
                              suggestions: List[str]) -> str:
        """Build the user prompt for the critic LLM call."""
        return (
            f"ORIGINAL REQUEST: {query}\n"
            f"REVIEWER VERDICT: {verdict}\n"
            f"REVIEW SCORE: {avg_score}\n"
            f"ISSUES: {json.dumps(issues, ensure_ascii=False)}\n"
            f"SUGGESTIONS: {json.dumps(suggestions, ensure_ascii=False)}\n"
            f"ITERATION: {self.iteration}/{self.MAX_ITERATIONS}\n\n"
            f"Make your decision: accept, reject, or iterate?"
        )

    def _parse_critique(self, response: str, query: str,
                         avg_score: float, issues: List[str],
                         suggestions: List[str]) -> AgentMessage:
        """Parse LLM critic response."""
        try:
            json_start = response.find("{")
            json_end = response.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                critique = json.loads(response[json_start:json_end])
                decision = critique.get("decision", "accept")
                reason = critique.get("reason", "LLM critic decided")
                next_agent = critique.get("next_agent")
                quality_score = critique.get("quality_score", avg_score)
                focus_areas = critique.get("focus_areas", [])

                # Validate decision
                if decision not in ("accept", "reject", "iterate"):
                    decision = "accept"

                # Determine next_agent based on decision
                if decision == "reject":
                    next_agent = "planner"
                elif decision == "iterate":
                    next_agent = next_agent or "executor"
                else:
                    next_agent = None

                return self._msg(
                    action="critic_verdict",
                    payload={
                        "decision": decision,
                        "reason": reason,
                        "next_agent": next_agent,
                        "iteration": self.iteration,
                        "quality_score": quality_score,
                        "issues_count": len(issues),
                        "suggestions": suggestions,
                        "focus_areas": focus_areas,
                        "query": query,
                    },
                    confidence=quality_score if decision == "accept" else quality_score * 0.5,
                )
        except (json.JSONDecodeError, ValueError):
            pass

        # Fallback: accept with current score
        return self._msg(
            action="critic_verdict",
            payload={
                "decision": "accept",
                "reason": "Could not parse critic response, accepting",
                "next_agent": None,
                "iteration": self.iteration,
                "quality_score": avg_score,
                "issues_count": len(issues),
                "suggestions": suggestions,
                "query": query,
            },
            confidence=avg_score,
        )

    def _fallback_critic(self, query: str, verdict: str,
                          avg_score: float, issues: List[str],
                          suggestions: List[str]) -> AgentMessage:
        """Rule-based critic decision when LLM is unavailable."""
        if verdict == "pass" or avg_score >= 0.7:
            decision = "accept"
            next_agent = None
            reason = "Quality threshold met"
        elif avg_score < 0.3:
            decision = "reject"
            next_agent = "planner"
            reason = "Quality too low, need to re-plan"
        else:
            decision = "iterate"
            next_agent = "executor"
            reason = "Content needs improvement"

        return self._msg(
            action="critic_verdict",
            payload={
                "decision": decision,
                "reason": reason,
                "next_agent": next_agent,
                "iteration": self.iteration,
                "quality_score": avg_score,
                "issues_count": len(issues),
                "suggestions": suggestions,
                "query": query,
            },
            confidence=avg_score if decision == "accept" else avg_score * 0.5,
        )
