#!/usr/bin/env bash
# self_context.sh — Agent self-trigger hook.
#
# Call this at the START of every reply to keep context_brief.json warm
# "без воли" — without the agent having to remember to call individual skills.
#
# Usage:
#   self_context.sh "user's message"
#
# Output: compact text summary of any new brief entries generated by
# auto-triggered skills. Empty output means no skills triggered.
#
# How it works:
#   1. Drop the message into .context/inbox/<ts>.json
#   2. Watcher daemon (running in background) picks it up
#   3. Daemon detects signals, dispatches matching skills in parallel
#   4. Skills write back to .context/context_brief.json
#   5. This script polls the brief for ~12s, prints new entries as text
#
# If daemon isn't running, this script will silently fall back to running
# watcher inline (still produces a brief, just blocking).

set -e
PROJECT_ROOT="/home/z/my-project"
SUPER_Z="$PROJECT_ROOT/bin/super-z"
DAEMON_PID_FILE="$PROJECT_ROOT/.context/watcher_daemon.pid"

# Auto-start daemon if not running
if [ ! -f "$DAEMON_PID_FILE" ]; then
    "$SUPER_Z" --daemon start >/dev/null 2>&1 || true
    sleep 0.5
elif ! kill -0 "$(cat "$DAEMON_PID_FILE" 2>/dev/null)" 2>/dev/null; then
    "$SUPER_Z" --daemon start >/dev/null 2>&1 || true
    sleep 0.5
fi

# Enqueue + wait for brief
exec "$SUPER_Z" --self-context "$@"
